### ISSUE TITLE
Integration test are failing

### ISSUE THREAD

**Issue by andrzej-casper** [make-software/casper-net-sdk#35]
**What happened?**

Integration tests are failing for me:

![image](https://github.com/make-software/casper-net-sdk/assets/121791569/edb18121-c770-4ffd-b3ac-12655bbaba2b)

@davidatwhiletrue could you trigger "Integration testing" workflow in order to verify this?

**Reproduction steps**

1. Build the latest `v2.0.0`:

```
$ git describe
v2.0.0
$ dotnet build
MSBuild version 17.4.8+6918b863a for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  Casper.Network.SDK -> /home/andrew/casper-net-sdk/Casper.Network.SDK/bin/Debug/net7.0/Casper.Network.SDK.dll
  Casper.Network.SDK.Test -> /home/andrew/casper-net-sdk/Casper.Network.SDK.Test/bin/Debug/net7.0/Casper.Network.SDK.Test.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.61
```

2. Run local network:

```
$ docker run --rm -it --name casper-nctl -d -p 11101:11101 -p 14101:14101 -p 18101:18101 -p 25101:25101 -e DEPLOY_DELAY="5sec" makesoftware/casper-nctl:latest
$ while [ "`docker inspect -f {{.State.Health.Status}} casper-nctl`" != "healthy" ]; do sleep 1; done
```

3. Configure PEM keys:

```
$ docker exec -t casper-nctl cat /home/casper/casper-node/utils/nctl/assets/net-1/faucet/secret_key.pem > Casper.Network.SDK.Test/TestData/faucetact.pem
````

4. Run tests:

```
$ dotnet test --no-build --verbosity normal --settings Casper.Network.SDK.Test/test.runsettings --filter="TestCategory=NCTL"
...
Failed!  - Failed:    26, Passed:    15, Skipped:     0, Total:    41, Duration: 614 ms
...
```

**26 failed tests** :fearful: 

Let us try again, this time using NCTL launched with `-e PREDEFINED_ACCOUNTS="true"`:

```
Build started 8/30/2023 12:09:02PM.
     1>Project "/home/andrew/casper-net-sdk/Casper.Network.SDK.sln" on node 1 (VSTest target(s)).
     1>ValidateSolutionConfiguration:
         Building solution configuration "Debug|Any CPU".
Test run for /home/andrew/casper-net-sdk/Casper.Network.SDK.Test/bin/Debug/net7.0/Casper.Network.SDK.Test.dll (.NETCoreApp,Version=v7.0)
Microsoft (R) Test Execution Command Line Tool Version 17.4.1+79d56b02b69a582cd90428878a5e9411ab7538f5 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed GetEraSummaryTest [25 ms]
  Error Message:
     Expected: True
  But was:  False

  Stack Trace:
     at NetCasperTest.NctlGetXTest.GetEraSummaryTest() in /home/andrew/casper-net-sdk/Casper.Network.SDK.Test/NctlGetXTest.cs:line 225
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.DelegatingTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

1)    at NetCasperTest.NctlGetXTest.GetEraSummaryTest() in /home/andrew/casper-net-sdk/Casper.Network.SDK.Test/NctlGetXTest.cs:line 225



Failed!  - Failed:     1, Passed:    40, Skipped:     0, Total:    41, Duration: 1 m 40 s - Casper.Network.SDK.Test.dll (net7.0)
     1>Done Building Project "/home/andrew/casper-net-sdk/Casper.Network.SDK.sln" (VSTest target(s)) -- FAILED.

Build FAILED.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:01:42.54
```

**Only 1 failed test!** This is much better, but still needs to be fixed.

**Comment by andrzej-casper** [comment]
Hmm, issue is not reproducible with CI/CD: https://github.com/make-software/casper-net-sdk/actions/runs/6023639426/job/16340766970.

**Comment by andrzej-casper** [comment]
After waiting few minutes, all tests passed successfully :tada: 

Seems that some time is required for the network initialization.

**Comment by davidatwhiletrue** [comment]
hi @andrzej-casper. thanks for reporting. As discussed separately, you local tests failed because the NCTL haven't completed the initialization when you triggered the tests. On the CI/CD pipeline this doesn't happen because the builld process takes time enough for NCTL to start signing blocks.
In any case, we'll consider to add a clear error message in this situation.
